// Add new bakes here directly. category must be "cookies", "cakes", "pastries", or "bread".
// croatianName is optional — only set it when a Croatian name is confirmed.
window.bakeryBakes = [
  { id: "bloody-berry-cake", name: "Bloody Berry Cake", image: "cakesection/bloody berry cake.png", alt: "Bloody Berry Cake", category: "cakes" },
  { id: "carrot-cake", name: "Carrot Cake", image: "cakesection/carrot cake.png", alt: "Carrot Cake", category: "cakes" },
  { id: "chocolate-cake", name: "Chocolate Cake", image: "cakesection/choclate cake.png", alt: "Chocolate Cake", category: "cakes" },
  { id: "ferero-cake", name: "Ferero Cake", image: "cakesection/ferero cake.png", alt: "Ferero Cake", category: "cakes" },
  { id: "jafa-cake", name: "Jafa Cake", image: "cakesection/jafa cake.png", alt: "Jafa Cake", category: "cakes" },
  { id: "kinder-bueno-cake", name: "Kinder Bueno Cake", image: "cakesection/kinder bueno cake.png", alt: "Kinder Bueno Cake", category: "cakes" },
  { id: "milrem-cake", name: "Milrem Cake", image: "cakesection/milrem cake.png", alt: "Milrem Cake", category: "cakes" },
  { id: "pineapple-cake", name: "Pineapple Cake", image: "cakesection/pineapple cake.png", alt: "Pineapple Cake", category: "cakes" },
  { id: "rafaelo-cake", name: "Rafaelo Cake", image: "cakesection/rafaelo cake.png", alt: "Rafaelo Cake", category: "cakes" },
  { id: "red-velvet-cake", name: "Red Velvet Cake", image: "cakesection/redvelvet.png", alt: "Red Velvet Cake", category: "cakes" },
  { id: "vanilla-cake", name: "Vanilla Cake", image: "cakesection/vanilla cake.png", alt: "Vanilla Cake", category: "cakes" },
  { id: "vesnas-raspberry-cake", name: "Vesna’s Raspberry Cake", image: "cakesection/vesnas rasberry cake.png", alt: "Vesna’s Raspberry Cake", category: "cakes" },
  { id: "walnut-chocolate-cake", name: "Walnut Chocolate Cake", image: "cakesection/walnut chocolate cake.png", alt: "Walnut Chocolate Cake", category: "cakes" },
  { id: "walnut-rum-cake", name: "Walnut Rum Cake", image: "cakesection/walnut rum cake.png", alt: "Walnut Rum Cake", category: "cakes" },
  { id: "white-egypt-cake", name: "White Egypt Cake", image: "cakesection/white egypt cake.png", alt: "White Egypt Cake", category: "cakes" },
  { id: "cookies-almond-nest-cookies", name: "Almond Nest Cookies", croatianName: "Badem Gnjezda", image: "cookies folder/Almond Nest cookies.png", alt: "Almond Nest Cookies", category: "cookies" },
  { id: "cookies-fererro-wafers", name: "Fererro Wafers", croatianName: "Ferero Oblatne", image: "cookies folder/Fererro wafers.png", alt: "Fererro Wafers", category: "cookies" },
  { id: "cookies-rafaelo-cookie", name: "Rafaelo Cookie", croatianName: "Rafaello Kuglice", image: "cookies folder/Rafaelo cookie.png", alt: "Rafaelo Cookie", category: "cookies" },
  { id: "cookies-decorated-cookies", name: "Sugar Cookies with Royal Icing", image: "cookies folder/Screenshot 2026-09-21 at 6.26.08 PM.png", alt: "Sugar Cookies with Royal Icing", category: "cookies" },
  { id: "cookies-vanilla-bean-cookies", name: "Vanilla Bean Cookies", croatianName: "Vanilice", image: "cookies folder/Vanilla Bean Cookies.png", alt: "Vanilla Bean Cookies", category: "cookies" },
  { id: "cookies-walnut-cookie", name: "Walnut Cookie", croatianName: "Kiflice s Orasima", image: "cookies folder/Walnut cookie.png", alt: "Walnut Cookie", category: "cookies" },
  { id: "cookies-bajadera", name: "Bajadera", image: "cookies folder/bajadera.png", alt: "Bajadera", category: "cookies" },
  { id: "cookies-basket-cookie", name: "Basket Cookie", croatianName: "Korpice", image: "cookies folder/basket cookie.png", alt: "Basket Cookie", category: "cookies" },
  { id: "cookies-coconut-cookie", name: "Coconut Cookie", croatianName: "Kiflice od Kokosa", image: "cookies folder/coconut cookie.png", alt: "Coconut Cookie", category: "cookies" },
  { id: "cookies-coconut-roll", name: "Coconut Roll", croatianName: "Rolada od Kokosa", image: "cookies folder/coconut roll.png", alt: "Coconut Roll", category: "cookies" },
  { id: "cookies-fig-walnut-cookies", name: "Fig & Walnut Cookies", croatianName: "Svekrvino Oko", image: "cookies folder/figandwalnutcookie.jpeg", alt: "Fig & Walnut Cookies", category: "cookies" },
  { id: "cookies-grandpa-s-mustache-cookies", name: "Grandpa’s Mustache Cookies", croatianName: "Djedov Brk", image: "cookies folder/grandmustache.jpeg", alt: "Grandpa’s Mustache Cookies", category: "cookies" },
  { id: "cookies-jam-cookie", name: "Jam Cookie", croatianName: "Linzer kolačići", image: "cookies folder/jam cookie.png", alt: "Jam Cookie", category: "cookies" },
  { id: "cookies-kolacki", name: "Kolacki", croatianName: "Kolački", image: "cookies folder/kolacki.png", alt: "Kolacki", category: "cookies" },
  { id: "cookies-orange-biscuit-cookies", name: "Orange Biscuit Cookies", croatianName: "Kolačići s Narančom", image: "cookies folder/orange buscuit cookie.png", alt: "Orange Biscuit Cookies", category: "cookies" },
  { id: "cookies-peach-cookie", name: "Peach Cookie", croatianName: "Breskve", image: "cookies folder/breskve.jpeg", alt: "Peach Cookie", category: "cookies" },
  { id: "cookies-wafer-rolls", name: "Wafer Rolls", croatianName: "Salame sa Oblatnom", image: "cookies folder/wafer roles.png", alt: "Wafer Rolls", category: "cookies" },
  { id: "cookies-walnut-jam-cookie", name: "Walnut Jam Cookie", croatianName: "Husarski uštipci", image: "cookies folder/walnut jam cookie.png", alt: "Walnut Jam Cookie", category: "cookies" },
  { id: "cookies-walnut-paws", name: "Walnut Paws", croatianName: "Šape od Oraha", image: "cookies folder/walnut paws.png", alt: "Walnut Paws", category: "cookies" },
  { id: "cookies-walnuts", name: "Walnuts", croatianName: "Orasi", image: "cookies folder/walnuts.png", alt: "Walnuts", category: "cookies" },
  { id: "cookies-cranberry-walnut-cookie", name: "Cranberry-Walnut Cookies", croatianName: "Kolačići s Brusnicom i Orasima", image: "cookies folder/Cranberry and walnut cookie.png", alt: "Cranberry-Walnut Cookies", category: "cookies" },
  { id: "pastries-baklava-pastry", name: "Baklava Pastry", image: "pastries/baklavapastry.png", alt: "Baklava Pastry", category: "pastries" },
  { id: "pastries-cherry-pastry", name: "Danube Waves", croatianName: "Dunavski Valovi", image: "pastries/cherry pastry.png", alt: "Danube Waves", category: "pastries" },
  { id: "pastries-chocolate-and-preserve-squares", name: "Gerbeaud Pastry", croatianName: "Žarbo Šnite", image: "pastries/chocolate and preserve squares.png", alt: "Gerbeaud Pastry", category: "pastries" },
  { id: "pastries-chocolate-layered-pastry", name: "Chocolate Layered Pastry", croatianName: "Mađarica", image: "pastries/chocolate layered pastry.png", alt: "Chocolate Layered Pastry", category: "pastries" },
  { id: "pastries-coconut-squares", name: "Coconut Squares", croatianName: "Kokos Kocke", image: "pastries/coconut squares-enhanced.png", alt: "Coconut Squares", category: "pastries" },
  { id: "pastries-cream-puffs", name: "Cream Puffs", croatianName: "Princes Krafne", image: "pastries/cream puffs .png", alt: "Cream Puffs", category: "pastries" },
  { id: "pastries-fruit-layered-pastry", name: "Fruit Layered Pastry", croatianName: "Voćna mađarica", image: "pastries/vocnemadarice.webp", alt: "Fruit Layered Pastry", category: "pastries" },
  { id: "pastries-lambada-pastry", name: "Lambada Pastry", image: "pastries/lambada pastry.jpeg", alt: "Lambada Pastry", category: "pastries" },
  { id: "pastries-nougat-squares", name: "Nougat Squares", croatianName: "Nugat Kocke", image: "pastries/nugatkokce.jpg", alt: "Nougat Squares", category: "pastries" },
  { id: "pastries-rafaellos-squares", name: "Rafaellos Squares", croatianName: "Rafaelo Kocke", image: "pastries/rafaellosquares.jpg", alt: "Rafaellos Squares", category: "pastries" },
  { id: "pastries-russian-hat-pastry", name: "Russian Hat Pastry", croatianName: "Ruske Kape", image: "pastries/russian hat.jpeg", alt: "Russian Hat Pastry", category: "pastries" },
  { id: "pastries-jaffa-wafer", name: "Jaffa Wafer", croatianName: "Jaffa Oblatne", image: "pastries/jafa wafer.png", alt: "Jaffa Wafer", category: "pastries" },
  { id: "pastries-lemon-layered", name: "Lemon Layered", croatianName: "Bijela Pita", image: "pastries/lemon layered.png", alt: "Lemon Layered", category: "pastries" },
  { id: "pastries-triple-delights", name: "Triple Delights", croatianName: "Trostruki Užitak", image: "pastries/tripple delgihts.png", alt: "Triple Delights", category: "pastries" },
];
